# Generated by Django 4.0.2 on 2022-04-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marmarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
